[package]
name = "social_economy_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "social_economy_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
once_cell = "1"

