apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
  REFRESH_SECRET_KEY: "replace-me"
  OTP_ENCRYPTION_KEY: "replace-me"
  DATABASE_PASSWORD: "replace-me"
