apiVersion: v1
kind: Secret
metadata:
  name: fastapi-rsa-keys
type: Opaque
stringData:
  private_key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY
    -----END RSA PRIVATE KEY-----
  public_key.pem: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_PUBLIC_KEY
    -----END PUBLIC KEY-----
